### ISSUE TITLE
bulk message is not working

### ISSUE THREAD

**Issue by dewanggaeka** [ookamiiixd/baileys-api#100]
I tried to send a message with 2 numbers but only the first number was sent and an error appeared in the postman / thunder bird client response (vs code)

postman
![image](https://user-images.githubusercontent.com/48443030/203694998-96bd9098-3170-446a-8d82-2009d6a8e093.png)

vscode
![image](https://user-images.githubusercontent.com/48443030/203695231-6c53b05c-abdc-4ef2-a1c9-fb1d4383ff7c.png)

**Comment by halowahyudi** [comment]
same issue.
TypeError: req.body.entries is not a function or its return value is not iterable
at sendBulk (file:///D:/DATA/learn/whatsapp-nodejs/controllers/chatsController.js:32:40)
....

**Comment by halowahyudi** [comment]
#101

**Comment by dewanggaeka** [comment]
> #101

after I tried changing the code it worked, but only for one time. I tried again and it turned out that the error was still the same as before, it was only sent to the first array. Is there a rule for sending bulk messages?

**Comment by halowahyudi** [comment]
what the error message?

**Comment by halowahyudi** [comment]
what is the error message?

**Comment by halowahyudi** [comment]
i have tried it and no problem

**Comment by dewanggaeka** [comment]
> what is the error message? because on me its work.

same as the picture in my post

**Comment by dewanggaeka** [comment]
> i have tried it and no problem

and I also tried to download your repository, and it still doesn't work

**Comment by ookamiiixd** [comment]
Should be fixed in the latest version
