### ISSUE TITLE
cannot send a message

### ISSUE THREAD

**Issue by riveleus** [ookamiiixd/baileys-api#104]
**request**
curl --location -g --request POST '127.0.0.1:8000/chats/send?id=john' \
--data-raw '{
    "receiver": "628231xxxxx", 
    "message": {
        "text": "hello this is bot!!"
    }
}'

**response**
{"success":false,"message":"Please fill out all required input.","data":{}}

**Comment by aeinstein** [comment]
API doc is wrong. 
USE:

curl --location -g --request POST '127.0.0.1:8000/chats/send?id=john'
--header 'Content-Type: application/json'
--data-raw '{
"receiver": "628231xxxxx",
"message": {
"text": "hello this is bot!!"
}
}'

**Comment by ookamiiixd** [comment]
Yeah i don't understand why postman request examples doesn't includes the headers. But the headers is there on the API docs, i suggest you to read more carefully next time.
