### ISSUE TITLE
Notifying frontend client of new msg

### ISSUE THREAD

**Issue by pablocruzpineda** [ookamiiixd/baileys-api#111]
How to notify frontend client when new msg has been received? Do I need to implement something like socket.io? Or how can I manage this with Baileys directly from the client side? Thanks for your answer.

**Comment by zahmadz** [comment]
Baileys is running on the server side, so you can't use baileys directly from the client side.

Yes, you need websocket/socket.io to implement that

**Comment by ookamiiixd** [comment]
Well that's depend, if you want to listen to realtime data, use Websocket or Server Sent Events. If you only need some callback, a webhook should be enough
