### ISSUE TITLE
npm install problem while run on server

### ISSUE THREAD

**Issue by ahmadhozien** [ookamiiixd/baileys-api#112]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @adiwajshing/baileys@5.0.0
npm ERR! Found: sharp@0.31.2
npm ERR! node_modules/sharp
npm ERR!   sharp@"^0.31.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional sharp@"^0.30.5" from @adiwajshing/baileys@5.0.0
npm ERR! node_modules/@adiwajshing/baileys
npm ERR!   @adiwajshing/baileys@"^5.0.0" from the root project
npm ERR!   peer @adiwajshing/baileys@"^5.0.0" from @ookamiiixd/baileys-store@1.0.0-beta.0
npm ERR!   node_modules/@ookamiiixd/baileys-store
npm ERR!     @ookamiiixd/baileys-store@"^1.0.0-beta.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: sharp@0.30.7
npm ERR! node_modules/sharp
npm ERR!   peerOptional sharp@"^0.30.5" from @adiwajshing/baileys@5.0.0
npm ERR!   node_modules/@adiwajshing/baileys
npm ERR!     @adiwajshing/baileys@"^5.0.0" from the root project
npm ERR!     peer @adiwajshing/baileys@"^5.0.0" from @ookamiiixd/baileys-store@1.0.0-beta.0
npm ERR!     node_modules/@ookamiiixd/baileys-store
npm ERR!       @ookamiiixd/baileys-store@"^1.0.0-beta.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/whatsapp/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/whatsapp/.npm/_logs/2023-01-08T13_17_06_053Z-debug-0.log

**Comment by zahmadz** [comment]
try 
`npm install --legacy-peer-deps`

**Comment by ookamiiixd** [comment]
Ah right, you could downgrade the `sharp` version into version `0.30.x` in the `package.json` file (recommended) or just use the `force` flag. I will create a PR for this later
