### ISSUE TITLE
Waiting for this message in groups

### ISSUE THREAD

**Issue by luispimenta** [ookamiiixd/baileys-api#114]
I have a list of groups, and sometimes randomly in some group, one of the messages is Waiting for this message.

What I noticed in the old version with the local file session, this happened between 1000 messages and only 1 was Waiting for this message.

I'm testing it now with the new version (which, by the way, turned out excellent) and this started to occur randomly in the groups, something between every 50 messages, 1 is Waiting for this message.

I know it's something from Whatsapp, but what surprises me is that keeping the session in a file hardly ever happens, this repo keeps the session with MongoDB https://github.com/salman0ansari/whatsapp-api-nodejs and it happens often too, I deduce that it's something in keeping the session in the database can contribute to that

@ookamiiixd do you have any idea what it could be?

**Comment by ookamiiixd** [comment]
I don't have a busy number when doing testing, so this never happened to me. Could you add below codes:
```ts
console.log({key, data});
```
in this [line](https://github.com/ookamiiixd/baileys-api/blob/4873c4d486941a904b0a8c0d28de7ab80b32fa35/src/wa.ts#L157), right before the return statement, so that i could debug it?

**Comment by mdestafadilah** [comment]
waiting message because your number is new, please type manual from wa in your phone.

**Comment by luispimenta** [comment]
> waiting message because your number is new, please type manual from wa in your phone.

The number is not new, I have it for more than 1 year, and as I mentioned, using the first version here of the project that keeps the session in a file, this almost does not happen, out of 1000 messages only 1, but testing now keeping the session in a database data, it happens more often, very strange, I will debug more tks.

**Comment by mdestafadilah** [comment]
Just back to first version, mine still working,

[862addeead75c53552154e4a1a028a39590732d5](https://github.com/ookamiiixd/baileys-api/tree/862addeead75c53552154e4a1a028a39590732d5)

btw, do you still investigating this debug?

**Comment by luispimenta** [comment]
> Just back to first version, mine still working,
> 
> [862addeead75c53552154e4a1a028a39590732d5](https://github.com/ookamiiixd/baileys-api/tree/862addeead75c53552154e4a1a028a39590732d5)
> 
> btw, do you still investigating this debug?

I couldn't identify the problem, but I think the problem is in the line number itself, because doing tests with a newer number, the problem doesn't happen, in the old number it sometimes happens. Thank you for your support, we continue using it and so far everything is stable, I will close this issue tks.
