### ISSUE TITLE
Need info for installing and getting to run

### ISSUE THREAD

**Issue by jhernancanom** [ookamiiixd/baileys-api#115]
In attached PDF my tryings.
Thanks.

[Procedimiento.pdf](https://github.com/ookamiiixd/baileys-api/files/10376276/Procedimiento.pdf)

**Comment by mdestafadilah** [comment]
what result?

**Comment by ookamiiixd** [comment]
Well, this project expect you to have basic knowledge about NodeJS. I could help you, feel free to reach me out on twitter

**Comment by jhernancanom** [comment]
> what result?

Sorry. I show in the PDF.... but here this is:

For starting:
1. After installing NodeJs, can I use 
   npm install
   npm run start:dev
as I did before?  

Thanks.
