### ISSUE TITLE
Getting started for beginners

### ISSUE THREAD

**Issue by davidgalih** [ookamiiixd/baileys-api#118]
I am very confused to start start this project.

I'm more familiar with the previous program code which I think is easier for me to run.

Is there a more detailed tutorial for beginners like me using typescript and prisma.io?

**Comment by mdestafadilah** [comment]
Using postman/ insomnia to test some endpoint, some detail you can check readme, there is some additional test, if you using PHP for consumsing this API, you could use CURL function.

**Comment by davidgalih** [comment]
Yes, I did it in this old repository project, and it worked well before using TypeScript. After this project was upgraded to use TypeScript, I am confused about where to start

**Comment by ookamiiixd** [comment]
I see. Fine, i'll update guide in the readme so that it could be easier to understand later

**Comment by davidgalih** [comment]
Thank you for understanding me as a novice user who is not well-versed in TypeScript and Prisma.io. I am happy to wait for tutorials for novice users like myself.

**Comment by lascimmia** [comment]
The same here. I'm unable to find `build` script, for example.
Beside: is it now mandatory to have a MySql instance?

**Comment by ookamiiixd** [comment]
> The same here. I'm unable to find `build` script, for example

Well, it's right there inthe [package.json](https://github.com/ookamiiixd/baileys-api/blob/3e48005f70c170f9ec035e6f7123e6626c45551f/package.json#L16) file
<br/>
>Beside: is it now mandatory to have a MySql instance?

Doesn't have to be MySQL, most of Prisma supported databases should do it. But yes, a database is required now

**Comment by mdestafadilah** [comment]
Hi royhan, any update about documentation?

**Comment by dewanggaeka** [comment]
just follow the installation and setup steps, i also don't understand about typescript but i managed to run it.
and to run the migration, I did the command `npm prisma migrate dev`

**Comment by ookamiiixd** [comment]
I'm sorry, still busy with other things recently. Maybe this weekend if i have the time

**Comment by ramphy** [comment]
What is the command to build? im trying: npx build, npm build... and i get problem.

`npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\58412\AppData\Local\npm-cache\_logs\2023-02-01T21_59_24_452Z-debug-0.log`

**Comment by dewanggaeka** [comment]
> What is the command to build? im trying: npx build, npm build... and i get problem.
> 
> `
> npm ERR! could not determine executable to run
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\58412\AppData\Local\npm-cache\_logs\2023-02-01T21_59_24_452Z-debug-0.log
> `

Try 'npm run build'

**Comment by rsaisankalp** [comment]
getting this error while running create {{BASE_URL}}/sessions/add

probably it is db connect issue. everything .env is seems fine, tried manually as well , it is connecting and migration is also successful , got the tables ported in db.. 

still getting this error :

pls help

{"level":50,"time":1675336136499,"pid":15487,"hostname":"MacBook-Air.local","err":{"type":"NotFoundError","message":"No Session found","stack":"NotFoundError: No Session found\n    at /Users/apple/code/nodejs/baileys-api/node_modules/@prisma/client/runtime/index.js:34062:15\n    at async /Users/apple/code/nodejs/baileys-api/node_modules/@prisma/client/runtime/index.js:34060:20\n    at async read (/Users/apple/code/nodejs/baileys-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:28:30)\n    at async useSession (/Users/apple/code/nodejs/baileys-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:50:20)\n    at async createSession (/Users/apple/code/nodejs/baileys-api/dist/wa.js:141:34)","code":"P2025","clientVersion":"4.7.1","name":"NotFoundError"},"msg":"An error occured during session read"}

**Comment by rsaisankalp** [comment]
> What is the command to build? im trying: npx build, npm build... and i get problem.
> 
> ` npm ERR! could not determine executable to run
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\58412\AppData\Local\npm-cache_logs\2023-02-01T21_59_24_452Z-debug-0.log `

yarn build

**Comment by mdestafadilah** [comment]
> getting this error while running create {{BASE_URL}}/sessions/add
> 
> probably it is db connect issue. everything .env is seems fine, tried manually as well , it is connecting and migration is also successful , got the tables ported in db..
> 
> still getting this error :
> 
> pls help
> 
> {"level":50,"time":1675336136499,"pid":15487,"hostname":"MacBook-Air.local","err":{"type":"NotFoundError","message":"No Session found","stack":"NotFoundError: No Session found\n at /Users/apple/code/nodejs/baileys-api/node_modules/@prisma/client/runtime/index.js:34062:15\n at async /Users/apple/code/nodejs/baileys-api/node_modules/@prisma/client/runtime/index.js:34060:20\n at async read (/Users/apple/code/nodejs/baileys-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:28:30)\n at async useSession (/Users/apple/code/nodejs/baileys-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:50:20)\n at async createSession (/Users/apple/code/nodejs/baileys-api/dist/wa.js:141:34)","code":"P2025","clientVersion":"4.7.1","name":"NotFoundError"},"msg":"An error occured during session read"}

are you try running with PM2 ?

**Comment by dewanggaeka** [comment]
how to send file?

**Comment by rsaisankalp** [comment]
> > getting this error while running create {{BASE_URL}}/sessions/add
> > probably it is db connect issue. everything .env is seems fine, tried manually as well , it is connecting and migration is also successful , got the tables ported in db..
> > still getting this error :
> > pls help
> > {"level":50,"time":1675336136499,"pid":15487,"hostname":"MacBook-Air.local","err":{"type":"NotFoundError","message":"No Session found","stack":"NotFoundError: No Session found\n at /Users/apple/code/nodejs/baileys-api/node_modules/@prisma/client/runtime/index.js:34062:15\n at async /Users/apple/code/nodejs/baileys-api/node_modules/@prisma/client/runtime/index.js:34060:20\n at async read (/Users/apple/code/nodejs/baileys-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:28:30)\n at async useSession (/Users/apple/code/nodejs/baileys-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:50:20)\n at async createSession (/Users/apple/code/nodejs/baileys-api/dist/wa.js:141:34)","code":"P2025","clientVersion":"4.7.1","name":"NotFoundError"},"msg":"An error occured during session read"}
> 
> are you try running with PM2 ?

no I am not running with pm2 , after yarn build, used yarn start thats it

**Comment by mdestafadilah** [comment]
> > > getting this error while running create {{BASE_URL}}/sessions/add
> > > probably it is db connect issue. everything .env is seems fine, tried manually as well , it is connecting and migration is also successful , got the tables ported in db..
> > > still getting this error :
> > > pls help
> > > {"level":50,"time":1675336136499,"pid":15487,"hostname":"MacBook-Air.local","err":{"type":"NotFoundError","message":"No Session found","stack":"NotFoundError: No Session found\n at /Users/apple/code/nodejs/baileys-api/node_modules/@prisma/client/runtime/index.js:34062:15\n at async /Users/apple/code/nodejs/baileys-api/node_modules/@prisma/client/runtime/index.js:34060:20\n at async read (/Users/apple/code/nodejs/baileys-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:28:30)\n at async useSession (/Users/apple/code/nodejs/baileys-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:50:20)\n at async createSession (/Users/apple/code/nodejs/baileys-api/dist/wa.js:141:34)","code":"P2025","clientVersion":"4.7.1","name":"NotFoundError"},"msg":"An error occured during session read"}
> > 
> > 
> > are you try running with PM2 ?
> 
> no I am not running with pm2 , after yarn build, used yarn start thats it

sometimes i bet this problem, remove node modules, lock file and install again then build, with different nodejs version, good luck, just test with different nodejs version

**Comment by rsaisankalp** [comment]
Still the same error with node 16 cleaned node modules same error

**Comment by rsaisankalp** [comment]
Same error with latest node 19 as well

**Comment by burhanmiroj** [comment]
{"level":50,"time":1675471136112,"pid":14052,"hostname":"Han","err":{"type":"PrismaClientKnownRequestError","message":"\nInvalid `model.create()` invocation in\nC:\\LETSDOTHIS\\whatsapp-gateway\\baileys-api\\node_modules\\@ookamiiixd\\baileys-store\\dist\\handlers\\message.js:79:27\n\n  76         },\n  77     },\n  78 }),\nΓåÆ 79 model.create(\nUnique constraint failed on the constraint: `PRIMARY`","stack":"Error: \nInvalid `model.create()` invocation in\nC:\\LETSDOTHIS\\whatsapp-gateway\\baileys-api\\node_modules\\@ookamiiixd\\baileys-store\\dist\\handlers\\message.js:79:27\n\n  76         },\n  77     },\n  78 }),\nΓåÆ 79 model.create(\nUnique constraint failed on the constraint: `PRIMARY`\n    at RequestHandler.handleRequestError (C:\\LETSDOTHIS\\whatsapp-gateway\\baileys-api\\node_modules\\@prisma\\client\\runtime\\index.js:34869:13)\n    at RequestHandler.handleAndLogRequestError (C:\\LETSDOTHIS\\whatsapp-gateway\\baileys-api\\node_modules\\@prisma\\client\\runtime\\index.js:34841:12)\n    at RequestHandler.request (C:\\LETSDOTHIS\\whatsapp-gateway\\baileys-api\\node_modules\\@prisma\\client\\runtime\\index.js:34836:12)\n    at async PrismaClient._request (C:\\LETSDOTHIS\\whatsapp-gateway\\baileys-api\\node_modules\\@prisma\\client\\runtime\\index.js:35926:16)\n    at async Promise.all (index 1)\n    at async EventEmitter.update (C:\\LETSDOTHIS\\whatsapp-gateway\\baileys-api\\node_modules\\@ookamiiixd\\baileys-store\\dist\\handlers\\message.js:68:17)","code":"P2002","clientVersion":"4.7.1","meta":{"target":"PRIMARY"}},"msg":"An error occured during message update"}

Hello everyone, i stuck at this error... this happened when i enable the chats.upsert code, maybe someone get same error like me?

**Comment by mdestafadilah** [comment]
> {"level":50,"time":1675471136112,"pid":14052,"hostname":"Han","err":{"type":"PrismaClientKnownRequestError","message":"\nInvalid `model.create()` invocation in\nC:\LETSDOTHIS\whatsapp-gateway\baileys-api\node_modules\@ookamiiixd\baileys-store\dist\handlers\message.js:79:27\n\n 76 },\n 77 },\n 78 }),\nΓåÆ 79 model.create(\nUnique constraint failed on the constraint: `PRIMARY`","stack":"Error: \nInvalid `model.create()` invocation in\nC:\LETSDOTHIS\whatsapp-gateway\baileys-api\node_modules\@ookamiiixd\baileys-store\dist\handlers\message.js:79:27\n\n 76 },\n 77 },\n 78 }),\nΓåÆ 79 model.create(\nUnique constraint failed on the constraint: `PRIMARY`\n at RequestHandler.handleRequestError (C:\LETSDOTHIS\whatsapp-gateway\baileys-api\node_modules\@prisma\client\runtime\index.js:34869:13)\n at RequestHandler.handleAndLogRequestError (C:\LETSDOTHIS\whatsapp-gateway\baileys-api\node_modules\@prisma\client\runtime\index.js:34841:12)\n at RequestHandler.request (C:\LETSDOTHIS\whatsapp-gateway\baileys-api\node_modules\@prisma\client\runtime\index.js:34836:12)\n at async PrismaClient._request (C:\LETSDOTHIS\whatsapp-gateway\baileys-api\node_modules\@prisma\client\runtime\index.js:35926:16)\n at async Promise.all (index 1)\n at async EventEmitter.update (C:\LETSDOTHIS\whatsapp-gateway\baileys-api\node_modules\@ookamiiixd\baileys-store\dist\handlers\message.js:68:17)","code":"P2002","clientVersion":"4.7.1","meta":{"target":"PRIMARY"}},"msg":"An error occured during message update"}
> 
> Hello everyone, i stuck at this error... this happened when i enable the chats.upsert code, maybe someone get same error like me?

cc @ookamiiixd  i think this problem in prisma ..

**Comment by ookamiiixd** [comment]
For those who having the prisma error logged, please discuss it on #136
