### ISSUE TITLE
Closed Connection, Error : Intentional

### ISSUE THREAD

**Issue by royhan97** [ookamiiixd/baileys-api#12]
Hi,

I starting to create new session via Postman, but I got Error like this

`Server is listening on http://127.0.0.1:8000`
`INFO [2022-02-25 15:16:51.615 +0000] (13268): closed connection, reason intentional
    class: "Baileys"
`
`WARN [2022-02-25 15:16:51.630 +0000] (13268): connect attempt 1 failed: Error: intentional
    class: "Baileys"
    error: {}`
`An error occured during connecting: Error: intentional`

Any solution?

Fyi, I use proxy or vpn. Perhaps any setting to handle this proxy connection?

Thank you.

**Comment by ookamiiixd** [comment]
Have you scan the QR within 20 seconds. I created a QR timeout mechanism there to avoid QR generation loop. So you have to scan the QR within 20 seconds or else an intentional logout request will be sent.

**Comment by royhan97** [comment]
The QR Code didn't appear in Dashboard page. But if use Postman, I got the response below

500 Internal Server Error

`{
    "success": false,
    "message": "Unable to create session.",
    "data": {}
}`

**Comment by ookamiiixd** [comment]
Are you trying to create a session for Multi-Device client?

Maybe you can try these first:
1. Create a legacy client session.
2. Create a session without proxy.

Let me know if both still failed in the QR generation.

**Comment by royhan97** [comment]
No, I trying with Single Device client

Yes, I successfully did both of them without proxy

I guess the issuee is in this proxy, maybe any config I can set to connect with my proxy?

**Comment by ookamiiixd** [comment]
I've never used a proxy before. How do you connect it?

Looks like you have to pass your proxy agent into the socket connect options when using proxy with baileys.

**Comment by royhan97** [comment]
I connect to internet with that proxy (set username, password and proxy port)

Yes, something like that. How I can set that "option" ?

**Comment by ookamiiixd** [comment]
Check out baileys connect options in the baileys docs. Sorry, i can't help you.
