### ISSUE TITLE
How to list all session Id's? 

### ISSUE THREAD

**Issue by pablocruzpineda** [ookamiiixd/baileys-api#124]
Can you let me know if is posible to list all the session Id's connected? Thanks

**Comment by ookamiiixd** [comment]
Not possible for now but i'll add a new endpoint for this later

**Comment by netrixken** [comment]
`curl --location --request GET 'http://localhost:3000/sessions'` produce `{"error":"URL not found"}`. is it implemented yet?

**Comment by ookamiiixd** [comment]
I have written the implementation in my local dev branch. I will push it after all of my todo list are done. Maybe this weekend
