### ISSUE TITLE
I cant send a message. Help me.

### ISSUE THREAD

**Issue by jovanlopez32** [ookamiiixd/baileys-api#126]
When I send a message with the correct values, as this:
[
    {
        "jid": "+521444547****@s.whatsapp.net",
        "type": "number",
        "delay": 5000,
        "message": {
            "text": "Hello!"
        }
    }
]

dont work, the error is the next:

{"errors":[{"msg":"Invalid value","param":"jid","location":"body"},{"msg":"Invalid value","param":"jid","location":"body"},{"msg":"Invalid value","param":"message","location":"body"},{"msg":"Invalid value","param":"message","location":"body"}]}

**Comment by ookamiiixd** [comment]
Seems like you're trying to send the `Send Bulk Message` route body into a `Send Message` route. Please read the docs carefully

**Comment by jovanlopez32** [comment]
I change the json, and I sen the next:
{
"jid": "5214445XXXXX@s.whatsapp.net",
"message": {
"text": "What's that @62823xxxx?"
}
}
And appears the same error:C

**Comment by jovanlopez32** [comment]
OK. I have include the header json in a post man. 

Header                                 Value
Content-Type                       application/json

Fixed, thnks.
