### ISSUE TITLE
Error on Route add Session - http://66.94.98.174:3000/sessions/add

### ISSUE THREAD

**Issue by thiago28x** [ookamiiixd/baileys-api#128]
Error log:

Server is listening on http://66.94.98.174:3000
{"level":50,"time":1674255703606,"pid":2885251,"hostname":"vmi985318.contaboserver.net","err":{"type":"PrismaClientValidationError","message":"\nInvalid `model.findUniqueOrThrow()` invocation in\n/opt/baile/baile-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:28:42\n\n  25 };\n  26 const read = async (id) => {\n  27     try {\n→ 28         const { data } = await model.findUniqueOrThrow({\n               select: {\n                 data: true\n               },\n               where: {\n                 sessionId_id: {\n                 ~~~~~~~~~~~~\n                   id: 'creds',\n                   sessionId: 'thiago'\n                 }\n               }\n             })\n\nUnknown arg `sessionId_id` in where.sessionId_id for type SessionWhereUniqueInput. Did you mean `pkId`? Available args:\ntype SessionWhereUniqueInput {\n  pkId?: Int\n  sessionId_userId_deviceId?: SessionSessionIdUserIdDeviceIdCompoundUniqueInput\n}\n\n","stack":"Error: \nInvalid `model.findUniqueOrThrow()` invocation in\n/opt/baile/baile-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:28:42\n\n  25 };\n  26 const read = async (id) => {\n  27     try {\n→ 28         const { data } = await model.findUniqueOrThrow({\n               select: {\n                 data: true\n               },\n               where: {\n                 sessionId_id: {\n                 ~~~~~~~~~~~~\n                   id: 'creds',\n                   sessionId: 'thiago'\n                 }\n               }\n             })\n\nUnknown arg `sessionId_id` in where.sessionId_id for type SessionWhereUniqueInput. Did you mean `pkId`? Available args:\ntype SessionWhereUniqueInput {\n  pkId?: Int\n  sessionId_userId_deviceId?: SessionSessionIdUserIdDeviceIdCompoundUniqueInput\n}\n\n\n    at Document.validate (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:29501:20)\n    at serializationFn (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:33060:19)\n    at runInChildSpan (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:22550:12)\n    at PrismaClient._executeRequest (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:33067:31)\n    at applyQueryExtensions (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:31416:19)\n    at consumer (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32992:18)\n    at /opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32997:51\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at /opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32997:29\n    at runInChildSpan (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:22550:12)","clientVersion":"4.9.0"},"msg":"An error occured during session read"}
/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:29501
    const error2 = new PrismaClientValidationError(renderErrorStr(validationCallsite));
                   ^

PrismaClientValidationError: 
Invalid `shared_1.prisma.session.upsert()` invocation in
/opt/baile/baile-api/dist/wa.js:170:35

  167 // socket.ev.on('chats.upsert', (data) => dump('chats.upsert', data));
  168 // socket.ev.on('contacts.update', (data) => dump('contacts.update', data));
  169 // socket.ev.on('groups.upsert', (data) => dump('groups.upsert', data));
→ 170 await shared_1.prisma.session.upsert({
        create: {
          id: 'session-config-thiago',
          sessionId: 'thiago',
          data: '{}',
      +   userId: String,
      +   deviceId: String,
      ?   expireAt?: BigInt | null,
      ?   createdAt?: BigInt | null,
      ?   updatedAt?: BigInt | null
        },
        update: {},
        where: {
          sessionId_id: {
          ~~~~~~~~~~~~
            id: 'session-config-thiago',
            sessionId: 'thiago'
          }
        }
      })

Argument userId for create.userId is missing.
Argument deviceId for create.deviceId is missing.
Unknown arg `sessionId_id` in where.sessionId_id for type SessionWhereUniqueInput. Did you mean `pkId`?

Note: Lines with + are required, lines with ? are optional.

    at Document.validate (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:29501:20)
    at serializationFn (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:33060:19)
    at runInChildSpan (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:22550:12)
    at PrismaClient._executeRequest (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:33067:31)
    at applyQueryExtensions (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:31416:19)
    at consumer (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32992:18)
    at /opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32997:51
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at /opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32997:29
    at runInChildSpan (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:22550:12) {
  clientVersion: '4.9.0'
}
root@vmi985318:/opt/baile/baile-api# node .
Server is listening on http://66.94.98.174:3000
  {"level":50,"time":1674258902484,"pid":2885717,"hostname":"vmi985318.contaboserver.net","err":{"type":"PrismaClientValidationError","message":"\nInvalid `model.findUniqueOrThrow()` invocation in\n/opt/baile/baile-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:28:42\n\n  25 };\n  26 const read = async (id) => {\n  27     try {\n→ 28         const { data } = await model.findUniqueOrThrow({\n               select: {\n                 data: true\n               },\n               where: {\n                 sessionId_id: {\n                 ~~~~~~~~~~~~\n                   id: 'creds',\n                   sessionId: 'john'\n                 }\n               }\n             })\n\nUnknown arg `sessionId_id` in where.sessionId_id for type SessionWhereUniqueInput. Did you mean `pkId`? Available args:\ntype SessionWhereUniqueInput {\n  pkId?: Int\n  sessionId_userId_deviceId?: SessionSessionIdUserIdDeviceIdCompoundUniqueInput\n}\n\n","stack":"Error: \nInvalid `model.findUniqueOrThrow()` invocation in\n/opt/baile/baile-api/node_modules/@ookamiiixd/baileys-store/dist/session.js:28:42\n\n  25 };\n  26 const read = async (id) => {\n  27     try {\n→ 28         const { data } = await model.findUniqueOrThrow({\n               select: {\n                 data: true\n               },\n               where: {\n                 sessionId_id: {\n                 ~~~~~~~~~~~~\n                   id: 'creds',\n                   sessionId: 'john'\n                 }\n               }\n             })\n\nUnknown arg `sessionId_id` in where.sessionId_id for type SessionWhereUniqueInput. Did you mean `pkId`? Available args:\ntype SessionWhereUniqueInput {\n  pkId?: Int\n  sessionId_userId_deviceId?: SessionSessionIdUserIdDeviceIdCompoundUniqueInput\n}\n\n\n    at Document.validate (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:29501:20)\n    at serializationFn (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:33060:19)\n    at runInChildSpan (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:22550:12)\n    at PrismaClient._executeRequest (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:33067:31)\n    at applyQueryExtensions (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:31416:19)\n    at consumer (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32992:18)\n    at /opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32997:51\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at /opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32997:29\n    at runInChildSpan (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:22550:12)","clientVersion":"4.9.0"},"msg":"An error occured during session read"}
/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:29501
    const error2 = new PrismaClientValidationError(renderErrorStr(validationCallsite));
                   ^

PrismaClientValidationError: 
Invalid `shared_1.prisma.session.upsert()` invocation in
/opt/baile/baile-api/dist/wa.js:170:35

  167 // socket.ev.on('chats.upsert', (data) => dump('chats.upsert', data));
  168 // socket.ev.on('contacts.update', (data) => dump('contacts.update', data));
  169 // socket.ev.on('groups.upsert', (data) => dump('groups.upsert', data));
→ 170 await shared_1.prisma.session.upsert({
        create: {
          id: 'session-config-john',
          sessionId: 'john',
          data: '{}',
      +   userId: String,
      +   deviceId: String,
      ?   expireAt?: BigInt | null,
      ?   createdAt?: BigInt | null,
      ?   updatedAt?: BigInt | null
        },
        update: {},
        where: {
          sessionId_id: {
          ~~~~~~~~~~~~
            id: 'session-config-john',
            sessionId: 'john'
          }
        }
      })

Argument userId for create.userId is missing.
Argument deviceId for create.deviceId is missing.
Unknown arg `sessionId_id` in where.sessionId_id for type SessionWhereUniqueInput. Did you mean `pkId`?

Note: Lines with + are required, lines with ? are optional.

    at Document.validate (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:29501:20)
    at serializationFn (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:33060:19)
    at runInChildSpan (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:22550:12)
    at PrismaClient._executeRequest (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:33067:31)
    at applyQueryExtensions (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:31416:19)
    at consumer (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32992:18)
    at /opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32997:51
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at /opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:32997:29
    at runInChildSpan (/opt/baile/baile-api/node_modules/@prisma/client/runtime/index.js:22550:12) {
  clientVersion: '4.9.0'
}

---------------------------------------------------------

Chat GPT suggestion:

It seems like an error is occurring in the session.js file, specifically in the following line:

Copy code
const { data } = await model.findUniqueOrThrow({
It looks like the error message is saying that an unknown argument sessionId_id is being used in the where clause of the findUniqueOrThrow method. The error message suggests that the correct argument name is pkId.

You should check the session.js file and make sure that the correct argument name is being used in the where clause of the findUniqueOrThrow method. Make sure that the sessionId_id is being replaced with pkId in the where clause of the findUniqueOrThrow method.

Also, it would be better if you can check the documentation of the findUniqueOrThrow method, to understand the correct usage of the method.

**Comment by ookamiiixd** [comment]
Seems like you've modified the table, please make sure you know what you're doing

If you explain what you're trying to achieve, i might be able to help

**Comment by thiago28x** [comment]
Hi, thanks for repliying,
yes this is not my usual stack, sorry about that.
Im just trying to setup the API.
I manually created a table inside mySQL and added the columns based on the prisma schema file but I'm guessing thats not the correct way?
