### ISSUE TITLE
Message not store while in chat.

### ISSUE THREAD

**Issue by kampit** [ookamiiixd/baileys-api#129]
If we are in a chat, the message is not saved to DB.

For now what I see the `message` column (table Message) will only be stored in the database if we are not in the chat.

Is it possible to keep all chat either chat or outside the chat.

**Comment by ookamiiixd** [comment]
I'll take a lot into this later

**Comment by kampit** [comment]
> I'll take a look into this later

Actually it works today. I don't have any issues to receive all message while in chat for now.
