### ISSUE TITLE
how to check device connected in session

### ISSUE THREAD

**Issue by Cloud-Dark** [ookamiiixd/baileys-api#13]
how to implementated conn.state == 'open' on this script?

**Comment by ookamiiixd** [comment]
You can check for the websocket state, it's available on `session.ws.readyState`. Then you can compare it with the [websocket contant](https://github.com/websockets/ws/blob/master/doc/ws.md#ready-state-constants).

**Comment by Sulivan1999** [comment]
> Você pode verificar o estado do websocket, ele está disponível em `session.ws.readyState`. Então você pode compará-lo com o conteúdo do [websocket](https://github.com/websockets/ws/blob/master/doc/ws.md#ready-state-constants) .

Hi, sorry to open this topic.

I need to implement a route to check the state of sessions, but I don't understand how I can get this information using `session.ws.readyState`, @ookamiiixd can you give me an example please?
