### ISSUE TITLE
Button issues for iOS

### ISSUE THREAD

**Issue by kampit** [ookamiiixd/baileys-api#130]
Do you have the same problem to send messages with buttons?

After I added `"viewOnce": true` Android device, app & web can receive this button. But on iOS no message is received.

```
{
  "jid": "xxxxxxx@s.whatsapp.net",
  "type": "number",
  "message": {
    "text": "Hi there. How are you?",
    "buttons": [
      {
        "buttonId": "id1",
        "buttonText": {
          "displayText": "Good"
        },
        "type": 1
      },
      {
        "buttonId": "id2",
        "buttonText": {
          "displayText": "Feeling button"
        },
        "type": 1
      }
    ],
    "viewOnce": true,
    "headerType": 1
  }
}
```

**Comment by whoiswhore** [comment]
same as me, "viewOnce": true, or false ios no message received

**Comment by ookamiiixd** [comment]
I don't have an iOS phone so i have no idea. Have you tried looking for the information in the baileys repo?

**Comment by thiago28x** [comment]
this is an issue with iPhones, even in other whatsapp libs like wppconnect :(

**Comment by kampit** [comment]
Actually it works! User and us need to communicate first. Don't send button at the first message. 

iOS can use the  button for any version.
