### ISSUE TITLE
How do i run migration on windows 10 ?

### ISSUE THREAD

**Issue by pasya1912** [ookamiiixd/baileys-api#131]
im new to this prisma thing. how do i run migration with it ? thanks

**Comment by pasya1912** [comment]
![image](https://user-images.githubusercontent.com/36727552/215071959-fa8549bf-78fe-4c6c-a978-48cf789cd448.png)
what should i do first ?

**Comment by kampit** [comment]
> ![image](https://user-images.githubusercontent.com/36727552/215071959-fa8549bf-78fe-4c6c-a978-48cf789cd448.png) what should i do first ?

Update your `.env` connection

`npx prisma migrate dev`

or

`npx prisma db push`
