### ISSUE TITLE
Add  a column to Message table

### ISSUE THREAD

**Issue by kampit** [ookamiiixd/baileys-api#133]
Is it possible for me to add a column to the `Message` table

For example, I added a `batchId` column to the `Message` table

Example:
```
{
  "jid": "62xxxx@s.whatsapp.net",
  "type": "number",
  "message": {
    "text": "Hello!"
  },
  "options": {
  	"batchId": "123"
  }
}
```

So on the `batchId` column I can store the value `123`.

Juts for reference column. Data will not send to WA. How to do that?

**Comment by ookamiiixd** [comment]
It's possible, but you need to extend the [baileys-store](https://github.com/ookamiiixd/baileys-store) library yourself
