### ISSUE TITLE
How can i send button with image

### ISSUE THREAD

**Issue by sairmali** [ookamiiixd/baileys-api#138]
now i am using for simple button messgae 

{
    "receiver": "918888888888888",
    "message": {
        "text": "hello there!",
        "footer": "hello",
        "templateButtons": [
            {
                "index": 1,
                "callButton": {
                    "displayText": "call Me",
                    "phoneNumber": "45555555"
                }
            },
            {
                "index": 2,
                "quickReplyButton": {
                    "displayText": "call Me",
                    "phoneNumber": "45555555"
                }
            },
            {
                "index": 3,
                "urlButton": {
                    "displayText": "call Me",   
                    "url": "45555555"
                }
            }
        ]
    }
}

but my question in how can i send image also in this ?

**Comment by ookamiiixd** [comment]
I don't know, maybe like [this](https://github.com/adiwajshing/Baileys/issues/2351) one?

**Comment by sairmali** [comment]
yes? good but how can do this when will send request
