### ISSUE TITLE
reconnection on restart

### ISSUE THREAD

**Issue by helpobras** [ookamiiixd/baileys-api#140]
I realized that baileys saves everything in the database... including session data...
however when giving a stop and then a start the system asks again to read the QRCODE... how do you do the automatic reconnection?
what if i need to update? do you have to reconnect everything again?

**Comment by helpobras** [comment]
sorry... I did the wrong procedure.

**Comment by jovial237** [comment]
Hello @helpobras how dis you solve the problem? I have the same issue.
Thanks.
