### ISSUE TITLE
How I can install this in my vps?

### ISSUE THREAD

**Issue by dmiffe** [ookamiiixd/baileys-api#144]
I would like a tutorial, please

**Comment by ookamiiixd** [comment]
I'm sorry but i don't have time to write a tutorial. It's pretty much the same about setting up any nodejs app. Maybe [this article](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-20-04) would help

**Comment by helpobras** [comment]
something very strange is happening... on my notebook I'm running the project and it opens normally at 3000...
however, when doing the same procedure on the VPS, port 3000 is not exposed.
just in case, I uploaded another project that I have on port 3001 of the server and it is exposing correctly...
what could be going on?
it's a VPS with nginx and ubuntu 22.04

Interestingly, if I do a reverse proxy pointing to domain.com -> 3000 it works...if I activate SSL the project runs but it doesn't accept using the routes.
