### ISSUE TITLE
Chat upsert does not provide sent/received message data

### ISSUE THREAD

**Issue by rahmat-why** [ookamiiixd/baileys-api#145]
I've done console.log but the sent/received message data doesn't appear

Code:
```
socket.ev.on('chats.upsert', (data) => {
    console.log(JSON.stringify(["UPSERT", data]))
})
```

Response:
`["UPSERT",[{"id":"628xx@s.whatsapp.net","conversationTimestamp":167xxx,"unreadCount":1}]]`

**Comment by ookamiiixd** [comment]
It's the default behavior of baileys event emitter and i couldn't do anything about it
