### ISSUE TITLE
Constraints on sending buttons

### ISSUE THREAD

**Issue by davidgalih** [ookamiiixd/baileys-api#149]
I have an unsolved problem when sending messages with the button, when I send a message with the button only I can see through my device on whatsapp web and no messages can be seen on the recipient's whatsapp.

**Comment by mohamad-supangat** [comment]
it is bug o bayleis

**Comment by davidgalih** [comment]
How can I see the bug, or is there a solution to fix it?

**Comment by AiceGate** [comment]
@mohamad-supangat Not Baileys bug. its work fine for me
![image](https://user-images.githubusercontent.com/99378880/220018120-cf4c14cc-dd05-45aa-879a-f15ba33586ee.png)

**Comment by davidgalih** [comment]
> @mohamad-supangat Not Baileys bug. its work fine for me
> ![image](https://user-images.githubusercontent.com/99378880/220018120-cf4c14cc-dd05-45aa-879a-f15ba33586ee.png)

May I know which version you can use?

**Comment by AiceGate** [comment]
> > @mohamad-supangat Not Baileys bug. its work fine for me
> > ![image](https://user-images.githubusercontent.com/99378880/220018120-cf4c14cc-dd05-45aa-879a-f15ba33586ee.png)
> 
> May I know what version you can use and how you send the message?
> 
> For your information, I'm using the latest version that uses typescript.

![image](https://user-images.githubusercontent.com/99378880/220041540-9cff0bde-8a62-49ec-9ef0-9d6b9e6594c2.png)

**Comment by davidgalih** [comment]
Thank you very much for the information, for Baileys Simple API are you using the pure Node js version or typescript?

**Comment by catursawahlunto** [comment]
I use pure javascript, I don't use typescript

**Comment by ookamiiixd** [comment]
1. Please provide an example of your request payload
2. Also, what kind of device the recepient is?

**Comment by davidgalih** [comment]
okay thank you very much, I have found the solution on this issue https://github.com/adiwajshing/Baileys/issues/2539#issuecomment-1436329734

**Comment by ookamiiixd** [comment]
I will close this then
