### ISSUE TITLE
Running "npm install"

### ISSUE THREAD

**Issue by jhernancanom** [ookamiiixd/baileys-api#152]
Hello, friends.

When I run **`npm install`**, I am getting the errs show in the image.
I aso attach the .log.

How should I proceed?

![image](https://user-images.githubusercontent.com/5818845/220006727-0ec51ecf-906b-4290-97fa-93f50a0c7c6d.png)

[2023-02-20T03_33_47_630Z-debug-0.log](https://github.com/ookamiiixd/baileys-api/files/10779446/2023-02-20T03_33_47_630Z-debug-0.log)

**Comment by ookamiiixd** [comment]
I'm not sure, have you tried searching solution in the internet?

**Comment by netrixken** [comment]
can confirm this. also after `npm install` success & running `npm build` got error:

`
> baileys-api@1.0.0-beta.0 build
> tsc

src/controllers/chat.ts:16:12 - error TS7006: Parameter 'c' implicitly has an 'any' type.

16     ).map((c) => serializePrisma(c));
              ~

src/controllers/chat.ts:42:12 - error TS7006: Parameter 'm' implicitly has an 'any' type.

42     ).map((m) => serializePrisma(m));
              ~

src/controllers/message.ts:20:12 - error TS7006: Parameter 'm' implicitly has an 'any' type.

20     ).map((m) => serializePrisma(m));
              ~

src/shared.ts:1:10 - error TS2305: Module '"@prisma/client"' has no exported member 'PrismaClient'.

1 import { PrismaClient } from '@prisma/client';
           ~~~~~~~~~~~~


Found 4 errors in 3 files.

Errors  Files
     2  src/controllers/chat.ts:16
     1  src/controllers/message.ts:20
     1  src/shared.ts:1`

**Comment by ookamiiixd** [comment]
@netrixken, actually, i've never used npm, i always use yarn instead. I'll take a look into this later

**Comment by kampit** [comment]
edit `tsconfig.json` and add

```
{
  "compilerOptions": {
    "noImplicitAny": false
  }
}
```

**Comment by ookamiiixd** [comment]
@netrixken i just realized that your error is most likely caused because you haven't setup your database before build. I'm sorry, this is my fault because of the wrong step in the guide

The correct step is actually after the step 3 of `Installation`, you have to do the `Setup` step before going into step 4. I'll update the guide asap

**Comment by jhernancanom** [comment]
Thanks, ookamiiixd.

**Comment by jhernancanom** [comment]
Hi, friends.
How should I proceed?
![image](https://user-images.githubusercontent.com/5818845/222645105-a406b45e-f9fb-43f8-817e-68b41ed9b466.png)

**Comment by jhernancanom** [comment]
My tryings in this week.
See attached PDF for my asking this time.
Thanks
 
[Procedimiento-2023-03-04.pdf](https://github.com/ookamiiixd/baileys-api/files/10890682/Procedimiento-2023-03-04.pdf)
![imagen-01-ReadMe](https://user-images.githubusercontent.com/5818845/222939633-2205775b-7b1d-4f7b-b305-e9613a522ca3.png)
![imagen-02-Setup](https://user-images.githubusercontent.com/5818845/222939634-302f9ce3-d9dd-4caa-ba5e-7a60238156cd.png)
![imagen-03-Env](https://user-images.githubusercontent.com/5818845/222939635-01701ba4-dbe3-4594-9e72-6316b5fdb2a3.png)
![imagen-04-Usage-n-API](https://user-images.githubusercontent.com/5818845/222939636-fb2ad99b-5e80-4a1e-9f09-4bebb14a1e61.png)
![imagen-11-](https://user-images.githubusercontent.com/5818845/222939637-8170c79f-d46f-4e49-84f6-8af7e95dcc4f.png)
![imagen-12](https://user-images.githubusercontent.com/5818845/222939638-0b73a60c-76d1-4061-b80f-1667f6b5b1bb.png)
![imagen-13](https://user-images.githubusercontent.com/5818845/222939640-38dd735c-79f4-406f-9a4b-d7c941ca2bdb.png)
![imagen-14](https://user-images.githubusercontent.com/5818845/222939641-10c23469-205d-466c-bba7-86144c03f5c6.png)
![imagen-15](https://user-images.githubusercontent.com/5818845/222939642-3fc96049-7af4-455c-a502-f5e6811b44ec.png)
![imagen-16](https://user-images.githubusercontent.com/5818845/222939643-af399692-5711-4ddb-81f4-7b4e2747bf96.png)
![imagen-17](https://user-images.githubusercontent.com/5818845/222939644-af8a4202-b009-4d4f-bd69-fa8123ae826a.png)
![imagen-18](https://user-images.githubusercontent.com/5818845/222939645-c87e6727-c64a-4152-9fc1-1365e74695d4.png)
![imagen-19](https://user-images.githubusercontent.com/5818845/222939646-daa7798f-08ce-4cb7-96d3-940f36b4e8f5.png)
![imagen-20](https://user-images.githubusercontent.com/5818845/222939647-2aa11e98-17b1-4415-9192-eff9c5cd2c42.png)
![imagen-21](https://user-images.githubusercontent.com/5818845/222939648-a1d69c61-b9dd-4a4f-97ce-fd3f9e08ddf1.png)
![imagen-30-KwRuntime](https://user-images.githubusercontent.com/5818845/222939650-fde83737-b4ab-45a0-8662-eb8c80e2627b.png)
![imagen-31-KwRuntime](https://user-images.githubusercontent.com/5818845/222939651-2a22bad0-c179-478b-b3cc-77577fd77462.png)

**Comment by jhernancanom** [comment]
Does the 

   "activeProvider": "mysql",

also needs to be changed in 

  ` .........\node_modules\.prisma\client\index.js`

in line 301?

and/or in

   `.........\node_modules\.prisma\client\schema.prisma`

????

**Comment by jhernancanom** [comment]
I am installing from scratch (ever and ever) (I wrote several .BAT files that help me to do it).

But when I got the Prisma-step, I am receiving a bunch of errors (I put text because it seems on GitHub we cannot put images); the errors start with (and go until line 160):

_**npx prisma db push**_

Environment variables loaded from .env

Prisma schema loaded from prisma\schema.prisma

Datasource "db": SQLite database "EMPRESA.db3" at "file:E:/baileys-waza/FACTURACION/EMPRESA.db3"

Error: P1012

error: Native type VarChar is not supported for sqlite connector.
  -->  schema.prisma:15
   |
14 |   pkId                      Int      @id @default(autoincrement())
15 |   sessionId                 String   @db.VarChar(128)
   |
error: Native type VarChar is not supported for sqlite connector.
  -->  schema.prisma:20
   |
19 |   createdAt                 BigInt?
20 |   createdBy                 String?  @db.VarChar(128)
   |
error: Native type VarChar is not supported for sqlite connector.
  -->  schema.prisma:21
   |
20 |   createdBy                 String?  @db.VarChar(128)
21 |   description               String?  @db.VarChar(255)
   |

**Comment by jhernancanom** [comment]
I am seeing that

Prisma [supported databases (click here)](https://www.prisma.io/docs/reference/database-reference/supported-databases). Tested on *MySQL* and *PostgreSQL*.

SQLite is included in Prisma, but not in Baileys-API.

I'll wait for SQLite in Baileys-API.

### What if do not wanna use a db?
What do I need to do in .ENV file to accomplish this?

**Comment by jhernancanom** [comment]
Hi, friends.

**Comment by jhernancanom** [comment]
-------------------------------------------------------
