### ISSUE TITLE
What's node  version must used?

### ISSUE THREAD

**Issue by mdestafadilah** [ookamiiixd/baileys-api#158]
Hi, i'm testing node 14 to 16 nothing to work!

```bash
failed to activate
> baileys-api@1.0.0-beta.0 start /www/wwwroot/apiwav3 > node . > baileys-api@1.0.0-beta.0 start > node . > baileys-api@1.0.0-beta.0 start > node . > baileys-api@1.0.0-beta.0 start > node . > baileys-api@1.0.0-beta.0 start /www/wwwroot/apiwav3 > node .
```

any one have this?

**Comment by jhernancanom** [comment]
[image: image.png]

**Comment by mdestafadilah** [comment]
> 

hallo?

**Comment by jhernancanom** [comment]
Sorry.

**Comment by jhernancanom** [comment]
Sorry.
I forgot that in GitHub nobody (other than me) can see images.

In the "Github Ookamiiixd Baileys-API" main page we can read this:
Requirements

   - *NodeJS* version *14.5.0* or higher


Transcript: *It is a requirement that you must have NodeJs v14.5.0 or
higher*.


Sorry for these drawbacks.

**Comment by mdestafadilah** [comment]
nothing to work, as you see in my describe, do you success? what node version using?

**Comment by mdestafadilah** [comment]
Ok i will be validate, i'm success using node 16.13.2

**Comment by jhernancanom** [comment]
Hi, **mdestafadilah**.
I have two customers with NodeJs-v16.15.1-x64 and an older version of Baileys (june- or july-2022), both running fine.

Now in my dev PC I am trying to install Baileys (march-03-2023) with NodeJs-v18.12.1-x64, but I am receiving errors referring to Prisma and SQLite.... and I'll be glad if you or someone can help me.

First errors (in this issue now in march-2023) were related to Git, but I have made it available.

Thanks.
