### ISSUE TITLE
Adding auto response

### ISSUE THREAD

**Issue by davidgalih** [ookamiiixd/baileys-api#164]
I have seen your update regarding reading incoming messages automatically, but how can I add a code if a certain message will be replied automatically. Suppose an incoming message Ping and will be replied to pong

**Comment by kevineduardo** [comment]
This is not a bot project. This is an API project. Use the API to send the message, and use the webhook (from the dev branch) to receive the message in YOUR application using this API.

**Comment by kevineduardo** [comment]
Bot Project for WhatsApp: https://github.com/adiwajshing/WhatsappInfoBot

**Comment by ookamiiixd** [comment]
As @kevineduardo said, your request is not really relevant. Thus, i can't fullfill your request for now

Even if i changed my mind, the best i can do is probably do a simple lookup in a DB and returns the corresponding response, 
 which should be easy to do it on your own by extending the project
