### ISSUE TITLE
can i create BOT for whatsapp ?

### ISSUE THREAD

**Issue by dewanggaeka** [ookamiiixd/baileys-api#165]
I saw on YouTube that the baileys repository can also be used to make BOT, is it possible to make BOT in this repo?

**Comment by dewanggaeka** [comment]
can BOT implementation be combined with this repo?

**Comment by kevineduardo** [comment]
Yes, it's open source, just fork it and edit it, or use as intended consuming the API provided.

**Comment by dewanggaeka** [comment]
> Yes, it's open source, just fork it and edit it, or use as intended consuming the API provided.

how?

**Comment by dewanggaeka** [comment]
okay, thanks everyone for helping. I've found how to make BOT.
simply by changing the contents of the wa.ts file then rebuild.
