### ISSUE TITLE
"closed connection, reason intentional"  after few seconds

### ISSUE THREAD

**Issue by aarvee022** [ookamiiixd/baileys-api#17]
Please check and provide solution for following error. 
After successful connection get following error within few seconds

```
INFO [2022-03-02 06:30:26.408 +0000] (5528): validated connection successfully
    class: "Baileys"
INFO [2022-03-02 06:30:26.413 +0000] (5528): opened connection to WhatsApp Web
    class: "Baileys"
INFO [2022-03-02 06:30:39.081 +0000] (5528): received 5893 contacts
    class: "Baileys"
INFO [2022-03-02 06:30:39.384 +0000] (5528): received 4181 chats
    class: "Baileys"
INFO [2022-03-02 06:30:44.280 +0000] (5528): closed connection, reason intentional
    class: "Baileys"
WARN [2022-03-02 06:30:44.283 +0000] (5528): connect attempt 1 failed: Error: intentional
    class: "Baileys"
    error: {}
An error occured during connecting: Error: intentional
```

**Comment by aarvee022** [comment]
It is working but sometimes I am getting this error.
as u can see connection was validated at 6:30:26 but it was closed on 6:30:44 so almost after 18 Seconds
and QR gets expired after 20 secs if not scanned so please check if there is any other issue.

**Comment by ookamiiixd** [comment]
Oh sorry, i didn't see that. Are you using the `Release v0.1-alpha` version?

**Comment by aarvee022** [comment]
I m using version 1.0.0 not alpha

**Comment by ookamiiixd** [comment]
Oh so you're using the older version of this repo?

Why don't you try to use the [Release v0.1-alpha](https://github.com/ookamiiixd/baileys-api/releases/tag/0.1-alpha) instead. Let me know if you're still facing this issue.

**Comment by aarvee022** [comment]
Can't use alpha version as if user manually logout from device then app crash.

**Comment by ookamiiixd** [comment]
> Can't use alpha version as if user manually logout from device then app crash.

That only occurs for **Multi-Device** client, you probably just want to use the *Legacy* one since the old version didn't support **Multi-Device** anyway.

**Comment by ookamiiixd** [comment]
I suppose you already found a solution for your problem. Closing this.

**Comment by aarvee022** [comment]
i m using alpha release now that problem is solved but now app crash after some time.
got following error
`Error: Unexpected status in 'action': Bad Request(400)
    at query (C:\baileys-api-master\node_modules\@adiwajshing\baileys\lib\LegacySocket\socket.js:273:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.chatRead (C:\baileys-api-master\node_modules\@adiwajshing\baileys\lib\LegacySocket\chats.js:93:9)
    at async EventEmitter.<anonymous> (file:///C:/baileys-api-master/whatsapp.js:93:17)
Running cleanup before exit.
`
Please check

**Comment by ookamiiixd** [comment]
Looks like the reading message is failed. And since i forgot to put the code inside `try...catch`, that error was thrown.

Well, the simplest solution was search and add a `try...catch` block in every async method. I forgot to do that in some part of the codes. I might update it later, but if you need it fast, then update it yourself for now.

**Comment by aarvee022** [comment]
try ..... catch is already added in get messages
`const getMessages = async (req, res) => {
    const session = getSession(res.locals.sessionId)

    /* eslint-disable camelcase */
    const { jid } = req.params
    const { limit = 25, cursor_id = null, cursor_fromMe = null } = req.query

    const cursor = {}

    if (cursor_id) {
        cursor.before = {
            id: cursor_id,
            fromMe: Boolean(cursor_fromMe && cursor_fromMe === 'true'),
        }
    }
    /* eslint-enable camelcase */

    try {
        let messages
        const useCursor = 'before' in cursor ? cursor : null

        if (session.isLegacy) {
            messages = await session.fetchMessagesFromWA(jid, limit, useCursor)
        } else {
            messages = await session.store.loadMessages(jid, limit, useCursor)
        }

        response(res, 200, true, '', messages)
    } catch {
        response(res, 500, false, 'Failed to load messages.')
    }
}

export default getMessages`

**Comment by ookamiiixd** [comment]
That's not the reading message, look at the produced error. It said the error is occured at `whatsapp.js:93`, which is the reading message implementation.

**Comment by aarvee022** [comment]
i have added try catch and problem is solved. but there is one more issue.
App hangs after few hrs. then it stops working. no error comes up.

**Comment by ookamiiixd** [comment]
Yeah, sometimes i faced the same issue too. I'll take a lot on my free time.

**Comment by aarvee022** [comment]
One more issue found. incoming messages are being marked as seen automatically.

**Comment by ookamiiixd** [comment]
Of course, you can simply delete or comment `whatsapp.js:86-98`.

**Comment by aarvee022** [comment]
Thanks  :)
it won't ban the number or create any other issue?

**Comment by ookamiiixd** [comment]
I'm not sure, but people said you should always read messages before sending messages. That's why i added that functionality just to make sure that every messages has been read before you sending a message.
