### ISSUE TITLE
Session Bug

### ISSUE THREAD

**Issue by jealvin** [ookamiiixd/baileys-api#18]
Session id found after refresh qrcode.

**Comment by ookamiiixd** [comment]
Can you add more details with your problem?

**Comment by saifulcoder** [comment]
> d found after refresh qrcode.

use qr requests each 20 second

**Comment by netrixken** [comment]
> How to refresh qr code without wait 20 second?

use different id or delete used id first

**Comment by jealvin** [comment]
> Can you add more details with your problem?
yes here is it : 
while request qrcode from post /session/add
im checking the user is connected using the session (/session/find/:id)
first time got "Session not found."
second request got "Session found."
waiting for a while got "Session not found."

**Comment by ookamiiixd** [comment]
Well, during QR generation the session status will be found no matter it's connected or not because the socket has been started and the session id is on use. Is this clear for you now?

**Comment by utqinadhif** [comment]
> > How to refresh qr code without wait 20 second?
> 
> use different id or delete used id first

Yes, i try to delete first, but how to check if connect?

**Comment by jealvin** [comment]
> > > > How to refresh qr code without wait 20 second?
> > > 
> > > 
> > > use different id or delete used id first
> > 
> > 
> > Yes, i try to delete first, but how to check if connect?
> 
> If you want to check if session has been successfully connected and authenticated, you can check for `user` properties. For **Beta Multi-Device** session, check in `session.user`. For **Legacy (Normal WhatsApp Web)** session, check in `session.state.legacy.user`. Both should return `undefined` if the session hasn't been authenticated.

then we need to add new router to check session user is hasn't been authenticated or not.

**Comment by ookamiiixd** [comment]
> > > > > How to refresh qr code without wait 20 second?
> > > > 
> > > > 
> > > > use different id or delete used id first
> > > 
> > > 
> > > Yes, i try to delete first, but how to check if connect?
> > 
> > 
> > If you want to check if session has been successfully connected and authenticated, you can check for `user` properties. For **Beta Multi-Device** session, check in `session.user`. For **Legacy (Normal WhatsApp Web)** session, check in `session.state.legacy.user`. Both should return `undefined` if the session hasn't been authenticated.
> 
> then we need to add new router to check session user is hasn't been authenticated or not.

Yep, i might do this if i have free time.

**Comment by ookamiiixd** [comment]
> > > > > > How to refresh qr code without wait 20 second?
> > > > > 
> > > > > 
> > > > > use different id or delete used id first
> > > > 
> > > > 
> > > > Yes, i try to delete first, but how to check if connect?
> > > 
> > > 
> > > If you want to check if session has been successfully connected and authenticated, you can check for `user` properties. For **Beta Multi-Device** session, check in `session.user`. For **Legacy (Normal WhatsApp Web)** session, check in `session.state.legacy.user`. Both should return `undefined` if the session hasn't been authenticated.
> > 
> > 
> > then we need to add new router to check session user is hasn't been authenticated or not.
> 
> yes, i do that, but for 20 second if i hit /session/add, the session still found, so how many seconds for session/add can create new qr?

typically 20 seconds.

**Comment by jealvin** [comment]
> > > > > > How to refresh qr code without wait 20 second?
> > > > > 
> > > > > 
> > > > > use different id or delete used id first
> > > > 
> > > > 
> > > > Yes, i try to delete first, but how to check if connect?
> > > 
> > > 
> > > If you want to check if session has been successfully connected and authenticated, you can check for `user` properties. For **Beta Multi-Device** session, check in `session.user`. For **Legacy (Normal WhatsApp Web)** session, check in `session.state.legacy.user`. Both should return `undefined` if the session hasn't been authenticated.
> > 
> > 
> > then we need to add new router to check session user is hasn't been authenticated or not.
> 
> Yep, i might do this if i have free time.

already create it add into whatsapp.js
```
const isLogedin = (sessionId) =>{
    const sessionFileLegacy = 'legacy_' + sessionId
    const sessionFileMD = 'md_' + sessionId
    var SESSION_FILE_PATH_LEGACY = join(__dirname, 'sessions', `${sessionFileLegacy}.json`);
    var SESSION_FILE_PATH_MD = join(__dirname, 'sessions', `${sessionFileMD}.json`);
    if (existsSync(SESSION_FILE_PATH_LEGACY) || existsSync(SESSION_FILE_PATH_MD) ) {
        return true
    }else{
        return false
    }    
}
```

**Comment by jealvin** [comment]
> > > > > > > How to refresh qr code without wait 20 second?
> > > > > > 
> > > > > > 
> > > > > > use different id or delete used id first
> > > > > 
> > > > > 
> > > > > Yes, i try to delete first, but how to check if connect?
> > > > 
> > > > 
> > > > If you want to check if session has been successfully connected and authenticated, you can check for `user` properties. For **Beta Multi-Device** session, check in `session.user`. For **Legacy (Normal WhatsApp Web)** session, check in `session.state.legacy.user`. Both should return `undefined` if the session hasn't been authenticated.
> > > 
> > > 
> > > then we need to add new router to check session user is hasn't been authenticated or not.
> > 
> > 
> > yes, i do that, but for 20 second if i hit /session/add, the session still found, so how many seconds for session/add can create new qr?
> 
> Typically 20 seconds, if you want to wait until it available then add some seconds. 25-30 seconds should do.

its better if you create socket to detect if new QR recieved or not

**Comment by ookamiiixd** [comment]
If this already clear for you guys, i will close this issue.
