### ISSUE TITLE
plase add send image and send video

### ISSUE THREAD

**Issue by Cloud-Dark** [ookamiiixd/baileys-api#23]
your code is powerfull,
but please add new feature send image & send video
thanks

**Comment by ariessetiyawan** [comment]
const sendImage = async (req, res) => {
    const session = getSession(res.locals.sessionId)
    const receiver = formatPhone(req.body.receiver)
    const { message, fileurl } = req.body
	
    try {
        const exists = await isExists(session, receiver)

        if (!exists) {
            return response(res, 400, false, 'The receiver number is not exists.')
        }
		const imagasend={
			 caption: message,
			 image: {
			  url: fileurl,
			 }
		}
		//console.log(imagasend)
        await sendMessage(session, receiver, imagasend)

        response(res, 200, true, 'The message has been successfully sent. send')
    } catch(e) {
        response(res, 500, false, 'Failed to send the message.'+e)
    }
}

**Comment by ariessetiyawan** [comment]
> your code is powerfull, but please add new feature send image & send video thanks

const sendImage = async (req, res) => {
const session = getSession(res.locals.sessionId)
const receiver = formatPhone(req.body.receiver)
const { message, fileurl } = req.body

try {
    const exists = await isExists(session, receiver)

    if (!exists) {
        return response(res, 400, false, 'The receiver number is not exists.')
    }
	const imagasend={
		 caption: message,
		 image: {
		  url: fileurl,
		 }
	}
	//console.log(imagasend)
    await sendMessage(session, receiver, imagasend)

    response(res, 200, true, 'The message has been successfully sent. send')
} catch(e) {
    response(res, 500, false, 'Failed to send the message.'+e)
}
}

const sendVideo = async (req, res) => {
    const session = getSession(res.locals.sessionId)
    const receiver = formatPhone(req.body.receiver)
    const { message,filename } = req.body

    try {
        const exists = await isExists(session, receiver)

        if (!exists) {
            return response(res, 400, false, 'The receiver number is not exists.')
        }
		const kirimvideo={
			caption:message,
			video: fs.readFileSync(filename), 
			gifPlayback: true
		}
        await sendMessage(session, receiver, kirimvideo)

        response(res, 200, true, 'The message has been successfully sent. send')
    } catch {
        response(res, 500, false, 'Failed to send the message.')
    }
}

**Comment by tukangparkir** [comment]
It easy code,

Kode yang sangat powerfull

**Comment by ookamiiixd** [comment]
Well...initially, i make this repo just as an example for the implementation. The baileys repo already covered on how to send various types of messages which you can find [here](https://github.com/adiwajshing/Baileys#sending-messages). It's pretty simple to achieve that. You should try to write your own codes.

But again to answer your question, maybe i'll add them later on my free time.
