### ISSUE TITLE
make io.connection 

### ISSUE THREAD

**Issue by tukangparkir** [ookamiiixd/baileys-api#27]
how to make io conection for convert QR code to web php or html ?

**Comment by ookamiiixd** [comment]
First, you should know how it works. My very first implementation uses websocket using `socket.io`, you can find it [here](https://github.com/ookamiiixd/baileys-api/tree/38cc01e96be32b10dace64c1da00fe90ff27009e). The codes may looks ugly but atleast it should give you an idea.
