### ISSUE TITLE
tidak support di cpanel

### ISSUE THREAD

**Issue by ilhamsk4** [ookamiiixd/baileys-api#29]
script ini saya pasang di cpanel gabisa pas saya run nodejs error unpacking ? token dan error lainya

**Comment by ookamiiixd** [comment]
Biasanya Cpanel menggunakan Phusion Passenger untuk support NodeJS, akan tetapi sepertinya terlalu strict untuk penggunaan ES Modulenya. Solusinya silahkan bisa coba transpile kodenya ke CommonJS terlebih dahulu atau mungkin rubah semua ekstensi filenya ke `.mjs` (jangan lupa untuk mengupdate importnya juga).

**Comment by aarvee022** [comment]
did you transpile it into one commom js?
