### ISSUE TITLE
Identifying the sender number/sessionId on messages.upsert

### ISSUE THREAD

**Issue by leenasn** [ookamiiixd/baileys-api#32]
Thank you for this codebase. It saved a lot of time for me.

I've multiple WhatsApp number connected and in the messages.upsert event how do I identify for which session/WhatsApp number the message is received for? Its not very clear for me. I checked Bailey docs too, but still not clear.

Thank you,
Leena

**Comment by ookamiiixd** [comment]
Well your event listener is most likely called under the `createSession` method right? You can simply access the `sessionId` from it parameter to determine which session the current listener is listening for.

**Comment by leenasn** [comment]
Oops my bad :(.

Thank you

**Comment by ookamiiixd** [comment]
No problem.
