### ISSUE TITLE
sticker support and webhook

### ISSUE THREAD

**Issue by kristen404** [ookamiiixd/baileys-api#35]
that would be cool if you add support for sticker, for example receiving an image and converting it to sticker or receiving a sticker and converting it to an image, also i saw a pr that is pretty interesting which implements webhooks and it's really useful

**Comment by ookamiiixd** [comment]
For stickers, it's more like a bot behavior which there's ton of repos for this on github already, so i won't do it.

For webhooks, i might consider it later on my free time.
