### ISSUE TITLE
app is getting crashed by itself

### ISSUE THREAD

**Issue by aarvee022** [ookamiiixd/baileys-api#37]
Hi,
Many times app is getting crashed by itself.
please check the log below.

{"level":50,"time":1651896672919,"pid":11656,"hostname":"vmi635923","msgId":"3EB0924B5E860F8724C5","params":["Bad MAC"],"msg":"failure in decrypting message"}
Error: Timed Out
    at C:\baileys-new\node_modules\@adiwajshing\baileys\lib\Utils\generics.js:178:32
Running cleanup before exit.

**Comment by ookamiiixd** [comment]
I'm not sure what the problem is. This should only occurred when there's bad session. There should be any relevant issues on baileys repo, try searching there first.
