### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by aarvee022** [ookamiiixd/baileys-api#43]
Hi,

I have added function to read messages in whatsapp.js

101. wa.ev.on('messages.upsert', async ({ messages }) => {
102. const m = messages[0]
103. const messageType = Object.keys (m.message)[0]

I was getting following error on message on messageType

TypeError: Cannot convert undefined or null to object
at Function.keys ()
at EventEmitter. (file:///C:/baileys-new/whatsapp.js:103:32)
at EventEmitter.emit (node:events:532:35)
at C:\baileys-new\node_modules@adiwajshing\baileys\lib\Socket\messages-recv.js:393:16
at processTicksAndRejections (node:internal/process/task_queues:96:5)
Running cleanup before exit.

then

Updated as solution provided by @vyxxr

100. wa.ev.on('messages.upsert', async (m) => {
101. const message = m.messages[0]
102. const messageType = Object.keys (message.message)[0]

Still getting errors

TypeError: Cannot convert undefined or null to object
at Function.keys ()
at EventEmitter. (file:///C:/baileys-new/whatsapp.js:102:32)
at EventEmitter.emit (node:events:532:35)
at C:\baileys-new\node_modules@adiwajshing\baileys\lib\Socket\messages-recv.js:393:16
at processTicksAndRejections (node:internal/process/task_queues:96:5)
Running cleanup before exit.

**Comment by aarvee022** [comment]
Please help. Really urgent

**Comment by ookamiiixd** [comment]
I just realized that `message.message` is can also be undefined since it was optional [https://adiwajshing.github.io/Baileys/interfaces/proto.IWebMessageInfo.html#message](here). Maybe you can add a condition checker before that line.

If you could provide me the result of `console.log(message)` there, maybe i could help you figure it out.

**Comment by ookamiiixd** [comment]
Since OP didn't reply to this issue after a while, i suppose this has been solved, closing this.
