### ISSUE TITLE
[INFO] useSingleFileAuthState deprecated

### ISSUE THREAD

**Issue by zakirkun** [ookamiiixd/baileys-api#46]
`**use multi file auth state instead please stores the full authentication state in a single JSON file
DO NOT USE IN A PROD ENVIRONMENT, only meant to serve as an example**`

[More Info](https://adiwajshing.github.io/Baileys/modules.html#useMultiFileAuthState)

**Comment by ookamiiixd** [comment]
Thanks for the information, but since currently it only available in Baileys main branch, i won't be able to update it because i've decided to only use Baileys stable release when possible.

Don't worry, i'll update it asap once available.

**Comment by ookamiiixd** [comment]
I just updated the restoring session mechanism in latest commits, please give it a try!

If you find any issue, please kindly open a new issue,
