### ISSUE TITLE
Set delay between bulk WhatsApp message 

### ISSUE THREAD

**Issue by hanumanjiblog** [ookamiiixd/baileys-api#47]
How to set delay between bulk WhatsApp message, please add this feature

**Comment by ookamiiixd** [comment]
Interesting, currently the sending message has 1 sec delay by default. I might consider it.

Thanks for your suggestion.

**Comment by nogats07** [comment]
I'll open a pr for this

**Comment by ookamiiixd** [comment]
> any update?? @ookamiiixd @nogats07

Maybe i could working on that this weekend.

**Comment by aarvee022** [comment]
Please update as soon as possible because  if we send bulk messages now number is getting blocked.

Thanks in advance.

**Comment by ookamiiixd** [comment]
> Please update as soon as possible because if we send bulk messages now number is getting blocked.
> 
> Thanks in advance.

How frequent your sending message activity is?

**Comment by ookamiiixd** [comment]
I just added this ability in latest commits. For the usage explanation, please check the `Send Bulk Message` section in the Postman doc. Please give it a try!

Keep in mind that this is only available for send bulk message.
