### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by nogats07** [ookamiiixd/baileys-api#48]
Thanks for this awesome API. I just want to ask, can this handle multiple connections at the same time? As I heard, javascript in nodejs is only single threaded, so if there are for example 3 connections trying to generate qrcode at the same time, will there be an issue?

Also, when we restart the script, does all sessions automatically started or we need to call some endpoint for that? I think this is mandatory to always receive messages from `message.upsert` event. If it needs endpoint trigger, do we also have an endpoint to check if session is already running?

**Comment by ookamiiixd** [comment]
> Thanks for this awesome API. I just want to ask, can this handle multiple connections at the same time? As I heard, javascript in nodejs is only single threaded, so if there are for example 3 connections trying to generate qrcode at the same time, will there be an issue?

Of cource, they're asynchronous so there's no problem with that.



> Also, when we restart the script, does all sessions automatically started or we need to call some endpoint for that?

No, your session information is stored into a json file. So when you (re)started the server, it'll load all existing sessions automatically.

> I think this is mandatory to always receive messages from `message.upsert` event.

Sorry, i don't understand what do you mean.

> do we also have an endpoint to check if session is already running?

We do, to simply check for a session exists or not, you can use the `Find Session` endpoint. We also have `Session Status` endpoint if you want to check the status of a session.

Hope this answer your question.

**Comment by AiceGate** [comment]
> I think this is mandatory to always receive messages from message.upsert event.

tidak harus mandatory !!, 
ini kan whatsapp api. kalo ingin mengelelola pesan yang diterima, tentu saja di event message.upsert.

**Comment by nogats07** [comment]
@ookamiiixd thanks for the reply. I see that there is bulk sending feature, does this work in the background or it will wait until all messages are sent before returning response?

**Comment by AiceGate** [comment]
> @ookamiiixd thanks for the reply. I see that there is bulk sending feature, does this work in the background or it will wait until all messages are sent before returning response?

Have you tried the bulk feature?.

Try it first and see what the response will be.
Either work in the background, or wait for all messages to be sent.

**Comment by noriellecruz** [comment]
@AiceGate unfortunately, I don't have numbers to test the bulk feature but based on the code, it won't work in the background.
