### ISSUE TITLE
how can I make request for reading message via API?

### ISSUE THREAD

**Issue by kupuii209** [ookamiiixd/baileys-api#51]
Hello how can I make request for reading message via API? Could you add this feature to portswigger please?

I am using (Baileys API v0.2).

`const lastMsgInChat = await getLastMessageInChat('123456@s.whatsapp.net') // implement this on your end
// mark it unread
await sock.chatModify({ markRead: false, lastMessages: [lastMsgInChat] }, '123456@s.whatsapp.net')`

**Comment by ookamiiixd** [comment]
I don't think it's really needed to be added into this project anytime soon. This project is intended to be simple and to the point. So for more advanced usage like this, i think you should implements it on your own so that you have full control on the flow.
