### ISSUE TITLE
The receiver number is not exists error

### ISSUE THREAD

**Issue by eizil** [ookamiiixd/baileys-api#54]
Hi,

I receive this error "The receiver number is not exists" a few times when the system idle for a while. I need to send a few times the same request, then only the app will send the msg successfully.

How can I fix this problem? seems like the app can't read the session for first few tries.

**Comment by eizil** [comment]
i think i found the fix for this issue, thanks.

**Comment by gadhiamitul41** [comment]
What is the fix?
