### ISSUE TITLE
Send message error

### ISSUE THREAD

**Issue by manojsitapara** [ookamiiixd/baileys-api#55]
I am getting following error. 

> TypeError: Cannot use 'in' operator to search for 'text' in Hello there!
>     at generateWAMessageContent (c:\Users\utrs\Downloads\baileys-api-master\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:193:16)
>     at generateWAMessage (c:\Users\utrs\Downloads\baileys-api-master\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:394:102)
>     at Object.sendMessage (c:\Users\utrs\Downloads\baileys-api-master\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:464:69)
>     at sendMessage (file:///c:/Users/utrs/Downloads/baileys-api-master/whatsapp.js:222:24)
>     at async send (file:///c:/Users/utrs/Downloads/baileys-api-master/controllers/chatsController.js:20:9) {stack: 'TypeError: Cannot use 'in' operator to search…i-master/controllers/chatsController.js:20:9)', message: 'Cannot use 'in' operator to search for 'text' in Hello there!'}

**Comment by ookamiiixd** [comment]
Your request payload?

**Comment by manojsitapara** [comment]
```
var axios = require('axios');
var qs = require('qs');
var data = qs.stringify({
  'receiver': '919857748589',
  'message': 'Hello there!' 
});
var config = {
  method: 'post',
  url: 'http://localhost:3000/chats/send?id=john',
  headers: { 
    'Content-Type': 'application/x-www-form-urlencoded'
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});
```

**Comment by ookamiiixd** [comment]
Seems like you're using the most few recents codes from this repo but you're referring to older Postman doc.

Make sure the documentation you read is compatible with the codes.

**Comment by ookamiiixd** [comment]
Since you reacted to my comment, is it solved now @manojsitapara?

**Comment by manojsitapara** [comment]
I have to test yet and close ticket in 1-2 hours

**Comment by ookamiiixd** [comment]
Okay, let me know if you got any other issues.

**Comment by manojsitapara** [comment]
working now
