### ISSUE TITLE
Photo Profile

### ISSUE THREAD

**Issue by saboy01** [ookamiiixd/baileys-api#6]
How i can get photo profile in getChatList ?

**Comment by ookamiiixd** [comment]
You can use the `getProfilePicture` method and pass the `jid` as the parameter. Please refer to [this section](https://github.com/adiwajshing/Baileys/tree/v3.5.3#misc).

**Comment by saboy01** [comment]
> You can use the `getProfilePicture` method and pass the `jid` as the parameter. Please refer to [this section](https://github.com/adiwajshing/Baileys/tree/v3.5.3#misc).

thanks brother, 
but i don't know how to display file image with index imageMessage.
this is url
url: "https://mmg.whatsapp.net/d/f/AqlOiIrHrf1KHoOdRsMZpumOWubiz9fmkHkPplrMVkMB.enc"

**Comment by saboy01** [comment]
![image](https://user-images.githubusercontent.com/50006426/153420438-5eaf63cf-2f3e-462d-9c74-79b7cf2d00c7.png)

**Comment by ookamiiixd** [comment]
Oh so you want to get an image message? you could try to download it using the existed baileys method, its already covered [here](https://github.com/adiwajshing/Baileys/tree/v3.5.3#downloading-media-messages)

**Comment by saboy01** [comment]
sory
