### ISSUE TITLE
can you please add scan and send message method in index.js for testing.

### ISSUE THREAD

**Issue by jasmanX** [ookamiiixd/baileys-api#60]
can you please add scan and send message method in index.js for testing. Thanks

**Comment by jasmanX** [comment]
// index.js
import 'dotenv/config'
import express from 'express'
import nodeCleanup from 'node-cleanup'
import routes from './routes.js'
import { init, cleanup } from './whatsapp.js'

const app = express()
const host = process.env.HOST ?? '127.0.0.1'
const port = parseInt(process.env.PORT ?? 8000)

app.use(express.urlencoded({ extended: true }))
app.use(express.json())
app.use('/', routes)

app.listen(port, () => {
    console.log(`Server is listening on http://${host}:${port}`);
    init();
})

nodeCleanup(cleanup)

export default app

**Comment by jasmanX** [comment]
// index.js
import 'dotenv/config'
import express from 'express'
import nodeCleanup from 'node-cleanup'
import routes from './routes.js'
import { init, cleanup } from './whatsapp.js'

const app = express()
const host = process.env.HOST ?? '127.0.0.1'
const port = parseInt(process.env.PORT ?? 8000)

app.use(express.urlencoded({ extended: true }))
app.use(express.json())
app.use('/', routes)

// scan method
app.get('/number/:instancesid/connect', async (req, res) => {
	instancesid = await scanQR(req.params.instancesid)
	const body = "<html><head><title>Scan QR</title><script>setTimeout(function(){window.location.reload();}, 1000);</script></head><body>@body</body></html>";
        const response = "<div><h5 style='text-align: center;' >Connected : " + req.params.instancesid + "</h5></div>";
        const result = body.replace('@body', response);
	res.send(req.params.instancesid+' connecting... '+req.params.instancesid); 
	});

// send message
sendMessage(id, { text: 'Thanks for code 😊' })

app.listen(port, () => {
console.log(Server is listening on http://${host}:${port});
init();
})

nodeCleanup(cleanup)

export default app

**Comment by ookamiiixd** [comment]
Sorry, i don't really get what do you mean. For testing purpose, you can always do it locally so this is not necessary.

**Comment by jasmanX** [comment]
ok will try myself :) Thanks for your response...
