### ISSUE TITLE
QR code

### ISSUE THREAD

**Issue by likaho** [ookamiiixd/baileys-api#62]
I wonder how I can get the QR code from terminal by calling api or requesting a html page.

**Comment by ookamiiixd** [comment]
If you set the `printQRInTerminal` value as `true` in the socket config, the QR should be printed in the terminal whenever a QR request received. By default i've set enabled this, see [here](https://github.com/ookamiiixd/baileys-api/blob/862addeead75c53552154e4a1a028a39590732d5/whatsapp.js#L65).

**Comment by likaho** [comment]
Thanks for your prompt response.  Following the [postman examples](https://documenter.getpostman.com/view/18988925/UVeNni36).

**Comment by likaho** [comment]
> If you set the `printQRInTerminal` value as `true` in the socket config, the QR should be printed in the terminal whenever a QR request received. By default i've set this enabled, see [here](https://github.com/ookamiiixd/baileys-api/blob/862addeead75c53552154e4a1a028a39590732d5/whatsapp.js#L65).

**Comment by ookamiiixd** [comment]
Make sure your request body content type is either urlencoded or json.

**Comment by likaho** [comment]
> Make sure your request body content type is either urlencoded or json.

**Comment by likaho** [comment]
Thanks!!
