### ISSUE TITLE
Notification (QR Callback) after create session

### ISSUE THREAD

**Issue by asyad85** [ookamiiixd/baileys-api#64]
hi, how to send a notification to the client using makeWASocket after the qr code scan is successful? tks

**Comment by ookamiiixd** [comment]
Unfortunately currently it's not possible. You have to write custom functionality using websocket / SSE to achieve that.

I already have a plan to add SSE support, but still not sure when i could started working on that.

**Comment by fikridev** [comment]
Hi may I know which function is triggered when the QR Code is scan so can build a way to listen to it in realtime using websocket
