### ISSUE TITLE
How to decrypt images received in message json 

### ISSUE THREAD

**Issue by yusufjk** [ookamiiixd/baileys-api#65]

**Comment by ookamiiixd** [comment]
Could you provide more information with this?

**Comment by yusufjk** [comment]
Currently when we recieve an image message it is sending a json object of decryption keys and the url of the image stored. Is it possible to retrieve the image with that information? Any methods which could be of help? I read the baileys guide but still couldn't properly understand the decryption process

**Comment by ookamiiixd** [comment]
I'll take a look into that when i have the time.

**Comment by ookamiiixd** [comment]
I've figured it out, i'll add the feature as a new route later
