### ISSUE TITLE
Trying to initiate

### ISSUE THREAD

**Issue by jhernancanom** [ookamiiixd/baileys-api#72]
How should I proceed?
Thanks.

![image](https://user-images.githubusercontent.com/5818845/178233735-50b23acb-390b-4c6c-bc9e-78fc80d45dd9.png)

![image](https://user-images.githubusercontent.com/5818845/178233559-45d19885-c988-4a80-a96c-7e17a9a403f8.png)

![image](https://user-images.githubusercontent.com/5818845/178234940-c63a5f65-cb08-40f2-8d5f-eb20154e9b99.png)

**Comment by nogats07** [comment]
This is a REST API for baileys, it's not a standalone app. Please read the **postman** documentation to know how to use it properly.

**Comment by ookamiiixd** [comment]
As mentioned by @nogats07, this is a Baileys implementation as an API service. Please refer to [API Docs section](https://github.com/ookamiiixd/baileys-api#api-docs) to learn more about the API. You may also want to check out the `examples` directory for reference.

Hope this answer your question. If you got any other issues, please kindly open a new one.
