### ISSUE TITLE
Tidak bisa di run di AZURE || Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by zeeid** [ookamiiixd/baileys-api#78]
Selamat pagi kak
ini saya deploy di azure kok tidak bisa ya
Lognya seperti ini :

> Fri Jul 29 2022 03:15:27 GMT+0000 (Coordinated Universal Time): **Application has thrown an uncaught exception and is terminated:Error [ERR_REQUIRE_ESM]: require() of ES Module** C:\home\site\wwwroot\app.js from C:\Program Files (x86)\iisnode\interceptor.js not supported.Instead change the require of app.js in C:\Program Files (x86)\iisnode\interceptor.js to a dynamic import() which is available in all CommonJS modules.at Module.patchedRequire [as require] (C:\PROGRA~2\SITEEX~1\NODEAP~1\293739~1.3\nodejs\node_modules\diagnostic-channel\dist\src\patchRequire.js:16:46)at Object.<anonymous> (C:\Program Files (x86)\iisnode\interceptor.js:459:1)Application has thrown an uncaught exception and is terminated:Error [ERR_REQUIRE_ESM]: require() of ES Module C:\home\site\wwwroot\app.js from C:\Program Files (x86)\iisnode\interceptor.js not supported.Instead change the require of app.js in C:\Program Files (x86)\iisnode\interceptor.js to a dynamic import() which is available in all CommonJS modules.at Module.patchedRequire [as require] (C:\PROGRA~2\SITEEX~1\NODEAP~1\293739~1.3\nodejs\node_modules\diagnostic-channel\dist\src\patchRequire.js:16:46)at Object.<anonymous> (C:\Program Files (x86)\iisnode\interceptor.js:459:1)

Error [ERR_REQUIRE_ESM]: require() of ES Module

Terimakasih

**Comment by mdestafadilah** [comment]
ES Module it's about nodejs version, please use node up 14.

**Comment by zeeid** [comment]
> ES Module it's about nodejs version, please use node up 14.

No.. it becose the script using type : module and azure need type : commonjs
