### ISSUE TITLE
Get name profile in get chat list

### ISSUE THREAD

**Issue by ravenero** [ookamiiixd/baileys-api#99]
How i get name in get chat list?

**Comment by ookamiiixd** [comment]
If you're using the latest version, it should be on the `name` properties

**Comment by ahmeaqas** [comment]
I am using the latest version (downloaded the zip, extracted, installed dependencies using npm install).

But when i do not retrieve name in while getting chat list (I have altered the number to avoid privacy issues).

`http://localhost:8000/chats?id=test`


`{
    "success": true,
    "message": "",
    "data": [
        {
            "id": "XXXX8345@s.whatsapp.net",
            "conversationTimestamp": 1671736757,
            "unreadCount": 1
        },
        {
            "id": "XXX041@s.whatsapp.net",
            "unreadCount": 0,
            "readOnly": false,
            "ephemeralExpiration": 0,
            "conversationTimestamp": "1671521393",
            "notSpam": true,
            "disappearingMode": {
                "initiator": "CHANGED_IN_CHAT"
            },
            "unreadMentionCount": 0,
            "tcToken": "AQHW6Vw8yZbL8G1wx+n6eJMyUppLkIBRgPZS+yFipa33Fd4=",
            "tcTokenTimestamp": "1671285660",
            "contactPrimaryIdentityKey": "D5b/Kke0EPxHJq+mRGmxI1Bfi35bvIL6pcwb2qY+oTI=",
            "tcTokenSenderTimestamp": "1671205745"
        },
        {
            "id": "XXXX7697335@s.whatsapp.net",
            "unreadCount": 0,
            "readOnly": false,
            "ephemeralExpiration": 0,
            "conversationTimestamp": "1671286553",
            "notSpam": true,
            "disappearingMode": {
                "initiator": "CHANGED_IN_CHAT"
            },
            "unreadMentionCount": 0,
            "tcToken": "AQHWEpa906RdlFxJjYjKLnLYMUYpIXPRo6JyStmSHZihtoI=",
            "tcTokenTimestamp": "1671286125",
            "contactPrimaryIdentityKey": "AVylP5+R4n4RFjwRi6P2lC7xIR3e/uDwn/hpSyLqrGg=",
            "tcTokenSenderTimestamp": "1671285735"
        },
        {
            "id": "XXXXXXX085687@s.whatsapp.net",
            "unreadCount": 0,
            "readOnly": false,
            "ephemeralExpiration": 0,
            "conversationTimestamp": "1671205872",
            "notSpam": true,
            "disappearingMode": {
                "initiator": "CHANGED_IN_CHAT"
            },
            "unreadMentionCount": 0,
            "contactPrimaryIdentityKey": "SLV4isrVf1typKUI+1gAH8fj2UIonHH9ocFhYDIh2wE=",
            "tcTokenSenderTimestamp": "1671205872"
        }
    ]
}`
